trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Bash@3
    inputs:
      filePath: "scripts/config.sh"
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-registry-chb-dev-1'
      repository: 'chabloom-transactions-frontend'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
