trigger:
  - master

pool: default

steps:
  - task: PowerShell@2
    inputs:
      filePath: "scripts/Config-Environment.ps1"
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"
  - script: |
      npm install -g yarn
      yarn install
      yarn build
    displayName: "yarn install and build"
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/build"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name).zip"
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
